name: Packer Application Build
on:
  pull_request:
    branches: [main]
env:
  AMI_USER: ${{ secrets.AMI_USER }}
  LATEST_AMI_ID: "***:ami-0e5c7eb966e2b6ee7"

jobs: 
  packer-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean install
        run: npm ci

      - name: Zip Files
        run: zip -r webapp.zip . 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Init
        run: packer init .

      - name: Packer Validate
        run: packer validate .

      # - name: Packer Build
      #   run: echo "AMI_ID=$(packer build -machine-readable . | awk -F, '$0 ~/artifact,0,id/ {print $6}')" >> $GITHUB_ENV

      - name: Configure AWS Credentials for Environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Launch Template Version
        run: aws ec2 create-launch-template-version --launch-template-id ${{secrets.LAUNCH_TEMPLATE_ID}} --source-version '$Latest' --launch-template-data '{"ImageId":"'$(echo ${{env.AMI_ID}} | sed 's/.*://')'"}'

      - name: Update Auto Scaling Group
        run: aws autoscaling update-auto-scaling-group --auto-scaling-group-name ${{secrets.AUTO_SCALING_GROUP_NAME}} --launch-template LaunchTemplateName=${{secrets.LAUNCH_TEMPLATE_NAME}},Version='$Latest'

      - name: Start Instance Refresh
        run: aws autoscaling start-instance-refresh --auto-scaling-group-name ${{secrets.AUTO_SCALING_GROUP_NAME}}
