name: Packer Application Build
on:
  pull_request:
    branches: [main]
env:
  AMI_USER: ${{ secrets.AMI_USER }}
jobs:
  packer-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean install
        run: npm ci

      - name: Zip Files
        run: zip -r webapp.zip . 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Init
        run: packer init .

      - name: Packer Validate
        run: packer validate .

      - name: Packer Build
        run: packer build .
